import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'

import { setAuthState, setAuthUser } from '@/shared/slices/authSlice'
import { useAppDispatch, useAppSelector } from '@/shared/hooks'

export default function Pagina2() {
  const authState = useAppSelector(state => state.auth.authState)

  const dispatch = useAppDispatch()

  const [userName, setUserName] = useState('')

  const handleLogin = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    dispatch(setAuthState(true))
    dispatch(setAuthUser(userName))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/">Para página 1</Link>
        <h1>{authState ? 'Autenticado' : 'Não autenticado'}</h1>
        <form onSubmit={handleLogin}>
          <input
            name="userName"
            type="text"
            placeholder="Set username"
            value={userName}
            onChange={e => setUserName(e.target.value)}
          />
          <button>Login</button>
        </form>
      </div>
    </>
  )
}
